package com.plannedwallet.accounts.models;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import java.util.HashMap;
import java.util.List;

@DynamoDBTable(tableName = "UserAccounts")
public class UserAccounts {

  private String userId;

  private List<HashMap<String, String>> accounts;

  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  @DynamoDBAttribute
  public List<HashMap<String, String>> getAccounts() {
    return accounts;
  }

  public void setAccounts(List<HashMap<String, String>> accounts) {
    this.accounts = accounts;
  }
}
