

##########################################################################################
# Dynamo DB configuration
##########################################################################################
amazon.dynamodb.endpoint: http://192.168.99.100:32219
amazon.aws.accesskey: key
amazon.aws.secretkey: key2

# -> TODO https://github.com/derjust/spring-data-dynamodb

##########################################################################################
# Actuator configuration
##########################################################################################
management:
  endpoints:
    web:
      base-path: /admin
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true