

##########################################################################################
# Dynamo DB configuration
##########################################################################################
amazon.dynamodb.endpoint: http://127.0.0.1:8000

##########################################################################################
# Actuator configuration
##########################################################################################
management:
  endpoints:
    web:
      base-path: /actuator
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true